version: '3.8'

services:
  parseflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parseflow-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_PATH=/app/logs/logs.db
      - RAW_LOG_CHAN_SIZE=2000
      - PARSED_LOG_CHAN_SIZE=2000
      - METRIC_CHAN_SIZE=200
      - BATCH_SIZE=200
      - FLUSH_INTERVAL=3s
      - SNAPSHOT_INTERVAL=30s
    volumes:
      - parseflow_data:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  parseflow_data:
    driver: local